# Bayesian

## Abstract

조건부 확률은 sample sapce가 $S$에서 $B$로 축소되었다는 것을 의미한다.

Bayesian의 Multiplication Rule은 사건이 시간순서대로 발생할 때 유용하게 사용될 수 있다.

set of events become **partition** of sample space $S$:
1. mutually exclusive(disjoint)
2. Pr of union $=1$

event $H$와 event $A$, $B$가 주어져 있다.  $A$와 $B$ 가 서로 독립이라면, $H$가 주어졌을 때 $A$가 추가되는 것이 $B$에 대한 정보를 아는데 영향을 미치지 않는다. 수식으로 증명가능.

$Dirichlet$, $Wishart$

$posterior odds$

### 변수의 독립성

$X_1 , \cdots, X_n$이 공통 sample space $S$를 갖는 변수이고 $\theta$ is unknown parameter.

if $S$, with for any subset(events) $A_1 , \cdots, A_n$, $Pr(X_1 \in A_1 , \cdots, X_n \in A_n \rvert \theta) = Pr(X_1 \in A_1 \rvert \theta) * \cdots *  Pr(X_n \in A_n \rvert \theta), then $X_1 , \cdots, X_n$ 는 $\theta$가 주어졌을 때 **조건부 독립**이다.

이는 앞서 말한 event의 독립성에 대응된다. 위의 독립성은 event의 독립성과 마찬가지로  $Pr(X_i \in A_i \rvert \theta, X_j \in A_j) = Pr(X_i \in A_i \rvert \theta) 가 성립. 이는 $\theta$가 주어졌을 때 $X_j$의 정보가 $X_i$에 대하여 아무런 추가정보를 주지 못함을 의미한다.

만약 세타가 주어진 상태에서 X1~Xn이 조건부 독립이라면 조건부 joint pdf는 각 조건부 margianl pdf의 곱과 같다. 만약 X-i가 모두 같은 분포를 따르면~. 이때 X_i들은 세타가 주어졌을 때 conditionally iid. 이는 marginal iid와는 구변된다. marginal iid는 X_i들의 marginal iid가 모두 같고 또한 독립이라는 소리. 



### 교환가능성

독립성은 엄격한 조건. 만족안되는 경우 많음. 이것보다는 약조건이 **교환가능성**. 독립성 $\rightarrow$ 교환가능성이지만 교환가능성 $\not \rightarrow$ 독립성. 교환가능성까지만 만족되면 De Finetti thm은 성립함.






