# (PART) 21-02  {-} 


# Survival Analysis
## Introduction

1. SA의 결과물은 보통 *time-to-event*, 즉슨 대부분의 경우에 nonnegative이며, 이는 곧 time domain을 한정함.
2. time-to-event의 distribution은 보통 *skewed*.
3. Survival data은 자주 *right censored*. 조사 대상자들은 조사 기간중에만 생존했음을 알며, 조사 기간 넘어서 죽으면 해당 시간이 정확히 기록되지 않음.
4. tail probability. 충분한 후속연구 후에는, tail of survival curve에 해당하는 subject들이 보통 되게 적음. estimation of the tail of the survival curve can be quite difficult. tail에서 survival density는 엄청 적어짐. 따라서 총 표본 수가 많이 확보되어 있지 않으면 tail에 해당하는 분석결과는 확보하기가 어렵다.



1. 모든 연구의 시간은 finite이므로 모든 subjects들에게서 발생한 event of interest 중 일부는 육안으로 관찰 못 할수도 있다. 장기적으로 발생은 했는데, 그게 우리 손닿는 곳에서 터지지 않았음.
2. 일반적으로 관측안된 failure time 들이 포함되어 있으면 기존 통계 테크닉은 사용할 수 없음.
3. failure time 이 관측되지 않은 subject들은 censored 되었다고 표현.
4. censored observations를 포함한 자료에서 정보를 뽑아내는 것이 SA의 estimation methods의 목적.



## Censoring Sources
1. Adminisitrative censoring
- event 발생 전에 연구 종료
often independent of failure time

2. Loss to follow-up

- subject들이 더이상 트랙 불과, 관찰 하에 있지 않음 (후속연구 개시했는데 예전에 살던 사람이 동네 떠났음)
censoring may be related (indirectly) to the failure time

3. withdrawl from study
- 너무 아프거나 증상이 낫던가 해서 연구에서 이탈
dependent censoring (*informative drop-out*), censoring이 failure time에 연관되어 있다는 점이 고민해야할 거리가 된다.





###### 임시방편

1. censor된 시간을 failure time으로 인식. $$\bar X \le E(X)$$ (underestimate).

2. censor 관측치를 전부 삭제. loss of infomration.



#### notation

$$T_i$$: potential failure time for the i-th subject
$$C_i$$: potential censoring time for the i-th subject
$$X_i = \min(T_i , C_i )$$ observed time
$$\delta_i = \begin{cases} 1, & T_i \le C_i & \text{(uncensored)} \\ 0, & T_i > C_i & \text{(censored)} \end{cases}$$






## 1. Right Censoring (most of the course)

Fail이 확실하게 터진 경우에만 fail, 이외의 경우에는 censor. 조사기간 종료까지 발병하지 않았거나, 이외의 이유로 종료 이전에 연구 이탈하면 양쪽 모두 censored.



#### Type of Data to be analyzed in survival analysis

1. Type Ⅰ Censoring:
특정 시점이 왔을 때 연구 종료. ex) 쥐한테 특정 영양소 먹이고 언제까지 생존하는지

  1) Progressive Type Ⅰ Censoring: 대상들이 다른, 고정된 sacrifice time 보유 ex) 도즈 레벨 4개로 나누고 각 그룹에 다른 sacrifice 기간 적용, 비용 효율화
  2) Generalized Type Ⅰ Censoring: subject들이 각각 다른 시기에 연구에 참여개시하고 정해진 시간에 연구 종료됨. subject가 참여할 때 censoring time 다 알려짐.



2. Type Ⅱ Censoring:
reliabilty 분석에서 흔함. 특정 횟수 failure 발생시 연구 종료.

※ Right Censoring: 개인의 정확한 survival time은 follow-up period의 우측에서는 incomplete해짐.



3. Random Censoring:
Censoring times are random.

※ let's focus on right censoring. Suppose $$T_1 , \cdots, T_n \sim f(t)$$ and $$C_1 , \cdots, C_n \sim g(c)$$. Then, we observe $$X_i = \min(T_i , C_i )$$ for $$i = 1, \cdots, n$$. In type Ⅰ censoring, $$C_i$$ is fixed (at $$C_r$$ or $$C_{r_i}$$). In random censoring, $$C_i$$ is random.


## 2. Left Censoring
less common in practice




$$
\begin{align}

\lambda(t) S(t)&= f(t) \\

\lambda(t) &= \dfrac{f(t)}{S(t)} \\

\lambda(t) &= \dfrac{f(t)}{} \dfrac{d}{dS(t)}\log S(t) \\


\end{align}
$$



$$
\begin{align}

\lambda(t) &= - \dfrac{d}{dt} \log S(t) \\

\lambda(t) &= - \dfrac {dS(t)}{dt} \dfrac{d}{dS(t)} \log S(t) \\

\lambda(t) &= - \dfrac {d[1-F(t)]}{dt} \dfrac{1}{S(t)} \\

\lambda(t) &= - (-f(t)) \dfrac{1}{S(t)} \\

S(t)\lambda(t) &= f(t)

\end{align}
$$

















  











$$
A = A'\; \; \; \Longrightarrow \; \; \; \exists \text{basis for } C(A):\text{constisting of evec of nonzero ev's.}
$$







linear transformation, span, trace, nonsingular, null space

$$
tr(ABC) = tr(BCA)=tr(CAB)
$$
$$
r(A_{n \times n})=r, \; \; \; r[\mathcal{N}(A)] = n-r
$$

$\lambda$ is ev of $A$, $v$ is evec of $A$.

$$
\begin{alignat}{3}

&\forall \lambda_i \not = 0 
&&\; \; \; \Longrightarrow \; \; \; 
&&
&& \forall v_i : 
&& span(v_i) \subset \mathcal{C}(A)

\\

&A = A', \; \lambda_i \not = \lambda_j 
&&\; \; \; \Longrightarrow \; \; \; 
&& v_i \perp v_j,
&&
&&span(v_i, v_j) \subset \mathcal{C}(A)


\\

&\exists A^{-1} 
&&\; \; \; \Longrightarrow \; \; \; 
&& \prod \lambda\not = 0
&&
&&

\\

&A = A'
&&\; \; \; \Longrightarrow \; \; \; 
&& 
&&
&&\exists \text{basis for } \mathcal{C}(A) \text{ consists of } v_i \text{ of } \lambda_i \not = 0



\\

&A_{n \times n} = A', \; \prod \lambda \not = 0 
&&\; \; \; \Longrightarrow \; \; \; 
&& \mathcal C (A)=\mathbb R^n,
&&
&&span( v) = \mathbb{R}^n



\\

&A_{n \times n} = A', \; \forall \lambda_i \not = 0 
&&\; \; \; \Longrightarrow \; \; \; 
&& 
&&
&&span(\forall v_i) = \mathcal{C}(A) \subset \mathbb{R}^n






\\

&A_{n \times n} = A', \; \forall \lambda_i  = 0 
&&\; \; \; \Longrightarrow \; \; \; 
&& 
&&
&&span(\forall v_i) = \mathcal{N}(A)

\\

&A = A'
&&\; \; \; \Longrightarrow \; \; \; 
&& 
&&
&&\mathcal{N}(A) = \mathcal C (A)^\perp

\\

&A_{n \times n} = A'
&&\; \; \; \Longrightarrow \; \; \; 
&& 
&&
&&


\exists v_i : span(v_i) = \mathcal C (A), \; v_i \perp v_j 
\; \; \tiny {\bigoplus} \; \; \normalsize \exists A^{-1} : \mathcal C(A) = \mathbb{R}^n
\; \; \tiny {\bigoplus} \; \; \normalsize \text{if normalized, orthonormal}

\end{alignat}
$$







































































