## Filtration의 개념을 정복하자!

도대체 Filtration(Filtration event)을 정복해야 하는 이유가 무엇인가?

금융공학 특히 금융수학을 공부하는데 있어서 가장 핵심이 되는 것 중에 하나가 Stochastic Differencial Equation 이다. 금융수학책들을 보면 다들 처음에는 확률(이 바닥에서는 측도론을 건드리는 것이 일반적)을 다룬 다음에 Stochastic Process를 다루고 Ito’s lemma를 거쳐 Black Sholes PDE 한번 찍어주고 Girsanov를 돌아서 Feynmman-Kac Theory로 끝내곤 한다.

특히 표준 금융수학 전반에 걸쳐서 Stochastic Process가 들어가는데 개인적으로는 이거 처음에 개념잡기가 힘들었다.. 왜냐하면 확률을 측도론(Measure Theory)에서 접근을 해야 하니 측도론을 조금은 알아야 하고(덧붙여 약간의 함수해석학…) Random process, Stopping Time… 등등… 이것들의 성질이 Ft-measurable이므로 Ft-measurable이라는 의미를 잘 알아야 할 필요성까지 있기 때문이다.

뭐 Ft-measurable, 좀더 분해해서 Ft라는 filtration 과 measurable이라는 성질을 논리적으로 완벽하게 정의하는데 드는 노력은 A4용지에 반정도 끄적이면 충분하다. 그러니 어디서 누가 물으면 답변하는 정도로는 그냥 암기해 버리면 그만이 아닐까 생각한다.

그러나 정의를 주저리주저리 외우고 다닌다고 하는 것은 그 대상을 아는 것은 아니다.… 애매한 문제에 엄밀한 판결을 내릴 수 있도록 능력이 되려면 수학적 정의가 포함하는 세계가 머리속에 익숙해 져야 한다고 생각한다. 

어째든지 Random process이던 Stopping Time 이건, Girsanov이건간에, 수학적인 내용이 나오면 적어도 머리속에는 간략화되고 가시적인 예제들이 Simulation되어야지 그 개념들이 ‘눈에’ 보이게 되는데 Filtration의 구체적인 모습들이 떠오르지 않으니까 나머지도 거기서 더 이상 이해가 되지 않았다. 이것이 본인이 Filtration을 한번 손봐야 겠다고 맘먹은 직접적인 동기이다.



### Random Process를 이야기 하기까지의 긴 여정의 요약

확률공간 (Ω, F, P)의 정의에 대해서 이야기하자면 많은 사람들이 이미 알겠지만 측도론(Measure Theory)에 대한 고된 과정을 거쳐야지만 비로서 이야기할 수 있게 된다. Measure Theory는 미적분 함수해석학 등을 최신(?)관점에서 접근하도록 만들어진 이론체계인데 실해석학(Real Analysis)이라는 과목에서 주로 다루게 된다. 여기에서 Measure라는 개념 – 우리말로 하면 측도 라는 것은 말 그대로 측정한다는 것인데 이런 류로 쉽게 생각할 수 있는 것은 ‘길이’ 이다…. 혹은 넓이, 부피, 기타 등등. 여기에 쓰이는 측도의 개념을 확률에다가 접근 시킨 사람이 콜모고로프라는 라는 것은 이미 널리 알려진 바이다. 길이, 확률의 기초적 개념은 초딩때 이미 섭렵했는데 굳이 어렵게 이해할 필요가 있는가 할 수도 있겠지만 아무래도 무한대이고 연속의 세계에서는 별의별 해괴한 일이 벌어지기 때문에 유치한(유치하다는 것은 경멸적인 이야기가 아니라 덜 세련된… 정도로 생각을 해주면 된다.) 차원의 접근방법은 더 이상 통하지 않고, 집합론, 해석학의 고등 주제들을 총 동원해야 모호한 문제에 비로소 해답을 내릴 수 있다. 그러니 해석학을 하기 위해서는 집합론을 먼저 알아야 하는데 이것도 중고딩때 하던 겉핥기 식의 집합론이 아닌 무한차원을 다룬 진검승부의 집합론이 필요하다.  하여튼지 간에 이렇게 금융수학을 공부하기 위해서 선행적으로 해야 할 아주 높은 산들이 산적해 있는데.. 이걸 다 언급하는 것은 이 글의 주제를 넘어서는 것 같구… 차후에 ‘금융수학을 공부하기 위한 로드맵’에 좀더 자세히 언급하겠다. 여기서 이야기 하고 싶은 것은 **확률과정**(Random Process)를 실해석학 위에서 가지고 노는 것은 나름대로 다 이유가 있다는 말을 하고 싶은 것이다. 기존의 유치한 확률론으로 접근해서 나름대로 이론을 쌓을 수 있다면 아주 happy한 case이지만 그렇다 하더라도 표준적으로 쓰여있는 paper나 text가 마팅게일이니, Girsanov니.. 이런 식으로 쓰여져 있으니 뭐라고 하는지 이해는 할 수 있어야 할 것 아닌가, 더욱이 수학이 어렵다고 하는데 솔직히 공부하는 것은 아주 어려운 것 맞다. 하지만 어려운 것은 익숙지 않다는 것뿐이다. 익숙해지면 세상이 참 쉽게 보인다. 복잡한 것은 수학이 아니라 세상이다. 공부하기 어려운 수학에 익숙해지면 복잡하게만 보였던 세상이 수학에 의해서 간략하게 보이게 된다. 세상 만만하게 보인다는 이야기이다. 어렵게 공부한 사람만 볼 수 있으니 개인적 보람도 아주 크다.





#### Sigma-Algebra(Sigma-Field)

Sigma-Algebra 라는 것은 measure를 다루기 위한 기본 개념인데 Sigma-Field와 같은 개념이다. 확률을 다루는 바닥에서는 Sigma-algebra 대신에 Sigma-Field라는 말을 쓴다. 참고로 Algebra, Field 라는 것은 Abstract Algebra(추상대수학)이라는 수학의 큰 줄기와 그 안의 체(Field)를 연상시키는데 연결고리에 대해서 약간의 심증은 가지고 있지만 물증은 찾지 못했다. 하여튼 간에 집합 A 위의 Sigma-Algebra(본인은 이 용어를 쓰겠다)의 정의는 다음의 말이 되는 A의 부분집합 E 들의 모임이다.
1.	공집합과 A는 Sigma-Algebra에 속한다.
2.	E가 Sigma-Algebra에 속하면 E의 여집합도 Sigma-Algebra에 속한다.
3.	E1과 E2가 Sigma-Algebra에 속하면 E1과 E2의 합집합도 Sigma-Algebra에 속한다.

뭐 여기까지는 상식적으로 이해가 된다. 

4.	Ei(I는 집합의 첨수족이고 자연수N의 원소이다) 가 Sigma-Algebra에 속하면 모든 Ei 의 합집합도 Sigma-Algebra에 속한다.

(3) 과 (4) 는 같은 이야기 인 것이 아닌가? 하는 의문이 있을 수 있겠다. 즉 (3)을 반복적으로 적용하면 결국 (4)가 아닌가 하는 생각이 바로 그것이다. 답은 “같지 않다”이다.  이것이 다르다는 것을 이해하는데 에는 집합론을 깊이 아는 것이 필요하다.  뭐 그것은 그러려니 하자…. 그런데 문제는 이것뿐만이 아니다. (4) 의 내용을 이렇게 바꾸어 말할 수 있는가? 
 
「Sigma-Algebra에 속하는 모든 E들을 무한히 합집합을 취한 것도 Sigma-Algebra에 속한다」

답의 yes, no 차원을 떠나서 위의 문제는 참으로 무책임한 질문이다. 왜냐하면 **무한히** 라는 것도 모호한 말이기 때문이다. 정확히는 **가부번수만큼** 합집합을 취한 것이 Sigma-algebra에 속한다.  가부번수라는 것은 자연수의 개수와 같으므로 위의 (4) 라는 표현을 쓴 것이다. 무한에는 가부번수라는 것도 있고 비가부번수가 있다. 짝수, 홀수, 자연수, 유리수등등 이것이 다 같은 개수를 가진다고 생각을 하고 그것을 가부번수라고 한다. 그리고 실수 무리수 같은 수는 비가부번 수이다. 그러므로 **(4) 에서 I 가 N 의 집합이 아닌 실수R의 집합이나. 무리수Qc 의 집합이라고 적어 놓으면 더 이상 Sigma-algebra가 아닌 다른 무엇이 되고 마는 것이다**. 
참고로 (4)의 조건이 없어지면 Sigma-algebra가 아닌 Algebra가 된다. 참고로 컴퓨터 이론의 기초를 이루는 2진수 연산인 **Bool algebra**(불대수)도 따지고 보면 여기서 말하는 algebra이다.  그리고 (3) 의 조건을 비가부번수까지 포함해서의 합집합에 대해서 라는 조건으로 바꾸어주고 유한개의 교집합에 대해서 닫혀 있으면 **위상(Topology)**가 된다. 이렇듯 쉽게 보이는 것도 엄밀하게 따지지 않으면 안 되는 이유가 바로 이것이다. 

무한이고 연속인 것을 머리 속에서 엄밀한 Simulation을 할 수가 없는데 이럴 경우 쉽게 볼 수 있는 간단한 discrete case를 가지고 머리 속에서 가지고 놀면 된다. 대상을 간단하게 한다고 하지만 그 대상에 대해서 무한과 연속을 다루는 규칙을 똑같이 적용하면 적어도 오류에 다다르지는 않는다. 그리고 때때로 그 결과는 그대로 연속일 때로 확장시켜 생각해도 된다. 물리학에서도 discrete로 모델을 만들고 모델을 미소변화량에 대한 연속모델로 만드는 것과 비슷하다. 게다가 **Caratheodory Extension**와 **Pi-System** 같은 도구들은 이론적으로 그러한 것이 타당하다는 보장까지 하니… 맘놓고 생각해도 된다. Caratheodory Extension 이니 Pi system이니 하는 것은 일단은 몰라도 된다. 이제 Sigma-Algebra에 대해서 조금 더 생각해 보자. 

A={w1,w2, w3} 

인 A의 **(2개의 원소를 가진)** Sigma Algebra $F$들을 구해보면

F1={ Ø, A} 

위 F1은 A위에서 Sigma Algebra의 1,2,3 을 만족시킨다. **유한집합이므로 3을 만족시키는 것은 4도 만족시킨다**. 하지만 **이것은 무한집합에서는 일반적인 것은 아니다**. 

F2={ Ø, {w1}, {w2,w3}, {w1,w2, w3}}

F3={ Ø, {w1}, {w2}, {w3}, {w1, w2}, {w2, w3}, {w1, w3}, {w1, w2, w3}}

어째든지 F1, F2, F3 셋 다 A위의 Sigma – Algebra이다. 그리고 F1⊆F2⊆F3이다. 

F1, F2, F3, 중에서 {w2, w3}을 포함하는 Sigma-Algebra 는 F2, F3이다. 그런데 F2와 F3중에서 크기가 작은 것은 F2이다. 즉 **F2는 {w2, w3}을 포함하는 가장 작은 Sigma-Algebra**이다. 이것은 {w2, w3}이 생성(generate)하는 Sigma-Algebra이다. 기호로는 Sigma({w2,w3}) 이다. 또한 Sigma({w1, w3})=F3이다. 그리고 짐작을 했겠지만 A의 모든 부분집합의 모임인 **P(A)가 가장 큰 Sigma Field이다**. 

어떤 집합(A)의 모든 열린집합들이 Generate하는 Sigma algebra를 **Borel Field** 라고 하고 B(A) 라고 쓰고 그 원소를 **Borel Set**이라고 한다. 어떤 집합이 실수의 집합이면 B(A)는 실수의 모든 열린집합들이 Generate하는 Sigma algebra 가 된다. 이딴거 어따쓰나 생각할지 모르겠지만 이것이 바로 **‘길이’** 라고 부를 수 있는 대상들의 모임인 것이다. 길이measure도 어렵게 말하면 lebegue measure라고 한다. 

머리에서 김 나겠지만 좀더 생각해 보자. **수직선 위의 어느 한 점으로 이뤄진 집합도, 그러한 점들이 자연수개수만큼씩 있는 집합도 다  __Borel set__이므로 길이를 생각할 수 있다**. 그 길이는 무엇일까? 답은 0 이다. 0과 1 사이의 모든 유리수 집합도 그 길이는 0이다. 가부번 집합의 길이는 0이 된다. **연속적인 실수의 구간은 역시 Borel set**이고 **양끝의 값의 차이가 당근 길이이다**. 그리고 그 구간에서 가부번 집합을 뺀 – 예를 들어 실수에서 유리수를 뺀 무리수의– 길이도 양끝 길이의 차이와 같다 왜냐하면 가부번 집합의 길이가 0이기 때문이다. **무리수구간의 길이**는 같은 끝점을 가진 실수 구간의 길이에서 유리수 길이를 빼야 하는데 **그 값, 즉 유리수의 길이,**이 0이므로 실수 구간의 길이와 같게 된다. 

**가부번 집합**이 아닌 경우에 반드시 길이가 있는가? 답은 No 이다. 칸토르 집합의 경우 **비가부번 집합**이지만 전체 길이는 0 인 황당한 case 가 있기는 있다. 

가부번, 비가부번 집합이란 둘 다 무한집합(원소의 개수가 무한개인 집합)을 의미한다.


참고로 측도가 0인 집합을  영집합(Null Set)이라고 하는데 해석학이건 확률론이건 확률미분방정식(Stochastic Differential Equation) 등에서 의외로 중요한 개념이므로 반드시 한번 더 보고 가자.

또한 실수에서 길이를 생각할 때 **__왜__ 실수집합의 __모든 부분집합__ 위에서 길이를 생각하지 않고 꼭 Borel Set위에서 정의를 하냐**고 생각할 수 있겠는데… 이것은 아마도 실수의 부분집합들 중에 길이의 대상이 되기에 부적합한 부분집합들이 존재하기 때문이라고 생각된다. 

솔직하게 이쯤 되면 이제 머리 속에서 속속들이 Simulation을 하는 것은 포기해야 한다. 어떤 집합은 (보통) 무한집합인데 무한집합의 Sigma-algebra를 적는 것은 사실상 불가능 할뿐더러 열린집합들의 모임이라는 것도 그리 생각하는 것이 쉽지 않다. 그러니 그것이 generate하는 것을 머리에 어떻게 떠올린다는 것인가? 수학도들은 숱한 반복적인 증명연습과 연습문제 풀이로 장님 코끼리 만지듯이 **감각을 키워나가지만** 문제는 시간이다… 하루아침에 되는 것이 아니기 때문이다. 

그렇지만 이것만 우선 먼저. 측도라는 것은 측정에 관한 이야기이다. 길이도 가장 간단한 측도이다. 길이의 대상이 되는 것들을 생각해 보자. 각각의 대상을 합해 놓아도 길이의 대상이 된다. 뿐만 아니라 **두 측도 값의 합이 바로 합집합의 측도값이 된다. Sigma–Algebra의 특성인 ‘합집합에 대해서 닫혀 있음’이 바로 이것을 의미한다. **

위의 A집합에 대해서 F2를 생각해 보자. 

F2={ Ø, {w1}, {w2,w3}, {w1,w2, w3}}

Ø → 0
{w1} → 0.4
{w2, w3} → 0.6
{w1,w2,w3} → 1

이렇게 Sigma Algebra의 각 값에 대해서 측도 값을 부여하였다. **물리적인 의미는 없고**, **측도의 논리**에 틀리지 않게 구성이 되어 있다. 한번 보자 “어떠한 원소들의 여집합이 Sigma Algebra의 원소이다.” 
확률의 경우를 생각해 보면 **어떤 사건이 일어난 확률이 __있다면__ 그것이 일어나지 않을 확률이 반드시 __있다__**는 의미와 같다. 

있다면 = $\sigma$-field에 속한다면
있다 = $\sigma$-field에 속한다

“어떠한 원소들의 합집합이 Sigma Algebra의 원소이다.”

또한 **두 독립적 사건의 확률을 각각 계산할 수 있다면 반드시 두 사건 중 하나가 일어날 확률도 계산할 수 있다**는 것을 의미한다. 
또한 **두 독립적 사건의 동시에 일어날 확률(합집합)은 각 확률(measure)의 합**이다. 

이러한 생각으로 위 측도값들을 보면 전혀 모순이 없다는 것을 알 수 있다. 물론 이러한 측도값은 하나만 있는 것이 아니다. 

Ø → 0
{w1} → 0.2
{w2, w3} → 0.8
{w1,w2,w3} → 1

이렇게 해도 부여한 측도값에는 전혀 문제 없다. 

<mark>
**그런데 {w2}에 대해서 측도값(확률)을 부여할 수 있는가?** 예를 들어 {w2}라는 사건이 존재한다면 뭐 억지로 어떤 값을 부여 했다고 하자. 그러면 {w2}가 일어나지 않는 경우에 대한 확률을 구할 수 있을까? 게다가 {w1} 또는 {w2}가 일어날 사건도 생각할 수 있는가? 대답할 수 없을 것이다. **이러한 예는 왜 확률을 생각할 때 Sigma Algebra를 생각해야 하는지를 설명해 준다.**
</mark>

즉, {2}는 가측(measurable)인가?




### Ft-measurable

위의 내용은 초보자에게는 접근할 수 있는 흥미를, 이미 내용을 알고 있는 사람들에게는 일종의 쉬어가는 페이지가 되었을 것 같다. 이제는 좀더 엄밀하게 접근을 하려고 한다. 

Ft-measurable 이라는 것은 Ft라는 Filtration에 measurable 하다는 이야기이다. **Filtration**은 Sample Space Ω 의 Sigma Algebra 들의 모임인데 Ft1⊆Ft2⊆Ft3 (t1<t2<t3) 로 되어 있어서 시간이 지날수록 점점 Sigma Algebra들이 이전  $\sigma$-Algebra를 포함하면서 커지도록 되어 있다. 이 절의 내용은 바로 이 Filtration의 몇 가지 가시적인 예제를 보여줄 것이고 그것이 엄밀한 수학적 정의와 어떻게 연결되는지를 따져 볼 것이다. 그렇게 해서 얻어진 가시적인 예제들은 장차 Stochastic Process에서 나오는 여러 가지 수학적인 개념들을 머리에서 Simulation 해서 각자의 이해의 영역으로 확보하는 과정에서 크나큰 역할을 하기만을 바랄 뿐이다. 

#### 가측(measurable)이란
먼저 measurable의 정의를 보자. Measurable의 의미를 따지기 전에 우선 임의의 하나의 함수를 생각해 보자. 그러한 함수는 집합A의 원소에서 실수로 간다고 하자. $f:A \Longrightarrow R

<pics>
				
위와 같은 예가 될 수 있겠다.

<mark>
그 다음은 역상에 대해서 생각해 보자. (역상도 집합이다.) A의 부분집합 Ω 위로의 역상은 $f^{-1} (E) = \{ x | x \in \Omega, \; f(x) \in E \subseteq B(R)\}$ 으로 정의된다. 

$f$의 정의역은 $A$, 치역은 $E$. 단, E는 보렐집합 (가측집합).
역함수, 역상과 $\sigma$-algebra의 관계는?

조금만 생각해 보면 $f^{-1}$는 결국 다음과 같은 하나의 함수이다. 

$$
f^{-1} : B(R) \rightarrow \sigma
$$


Sigma($\sigma$)는 (Ω 위의 = $\Omega$가 생성하는) Sigma algebra이다. 즉 정의구역은 Borel Set($B(R)$) 들이고 공변역(치역)은 Ω의 Sigma algebra이다. 
</mark>
 



E는 실수의 Borel set 의 원소이다. 모든 E를 다 여기서 명세할 수는 없지만 몇가지 경우로 분류할 수는 있다. 
1.	r1을 원소로 포함한 E들 — 이것들의 무리를 E1이라고 하자
2.	r1를 원소로 포함하지 않는  E들 — 이것들의 무리를  E1’이라고 하자

$$
\begin{align}
E &= E_1 \cup E_2
E_1 \cap E_2 &= \emptyset
\end{align}
$$

E1에 속한 E의 경우 $f^{-1}(E)$ 는 Ω가 된다. <mark>Check it!</mark>
E1’에 속한 E의 경우 $f^{-1}(E)$ 는 Ø가 된다. <mark>Check it!</mark>

이때 주의해야 할 점은 E의 원소로 r2, r3, r4, 가 있는 경우이다. 이 경우 이들에 대한 f의 역함수 값은 A에는 존재할 수도 있다. 하지만 Ω의 원소 중에는 그런 없기 때문에 Ø 되는 것이다. 다시 한번 정의를 살펴보자.
$f^{-1} (E) = \{ x | x \in \Omega, \; f(x) \in E \subseteq B(R)\}$ 이다. x는 Ω의 원소이어야만 한다. 그런 원소가 아니면 공집합이 된다. 
Ω 와 Ø 의 모임인 {Ω , Ø} 는 Ω 위의 Sigma algebra 이다. 특별히 Ω 가 Generate하는 Sigma algebra 라고 한번 생각해 주고 넘어가자. 

이제 measurable의 정의를 보자. 

함수 f: Ω → R이 F – measurable 이면, $f^{-1} (E) = \{ x | x \in \Omega, \; f(x) \in E \subseteq B(R)\}$ 가 Ω 위에서 Sigma Algebra F의 원소이다. 

그런데 어떤 책에서는 

함수 f: Ω → R이 F – measurable 이면 $f^{-1} (E) = \{ x | x \in \Omega, \; f(x) \in E \subseteq B(R)\}$ 가 Ω 위에서 Sigma Algebra 를 이룬다. 

라고 해서 사람을 헷갈리게 만든다. 이게 왜 사람 헷갈리게 만드는가 하면 F 안의 원소인 e1의 상이 B(R) 의 원소가 아닐 경우 위의 두 개의 정의는 동치가 되기 때문이다. 
아직 이 문제는 개인적으로는 해결이 안되었고 학습에는 그다지 큰 문제는 아니므로 첫 번째 정의를 받아들이자. 

#### Filtration
 
##### t =0 일때 Ft

Ω={w1, w2, w3, w4} 라고 하자. 

<pics>

B(R) 들의 원소 들 E 들은  r1 을 원소로 같는 E 들의 무리 E1 이 있고 그렇지 못한  무리 E2 가 있을 수 있다. 
앞의 경우에서 해설한 바 몇 가지 점을 유의하면 다음과 같은 결과를 얻는다.

1.	무리 E1 들의 역상은 Ω 이다. 
2.	무리 E2 들의 역상은 Ø 이다. 
3.	따라서 B(R)의 모든 역상들의 모임은 {Ω, Ø} 이다. 
4.	Ft(t=0) = F0 을 {Ω, Ø}이라고 하면 함수 f 는 위 정의에 의하여 F0 measurable이다. 
5.	결과적으로 보니까. F0는 partition{Ω, Ø} 이 generate하는 Sigma Algebra로 볼 수 있다.


##### t =1 일 때 Ft

<pics>

앞에서와 같이 B(R)을 다음과 같이 나눌 수 있다. 그리고 앞에서 한 분석을 다시 해보면 다음과 같은 결과가 나온다. 

| E의 그룹 | 그룹의 성격 | 그룹내 모든 E들의 역상 |
|:-:|:-:|:-:|
| E1 | r1 을 원소로 갖는  E들 | {w1} |
| E2 | r2 을 원소로 갖는  E들 | {w2, w3, w4} |
| E12 | r1과 r2 모두를 원소로 갖는 E들 | {w1, w2, w3, w4} |
| En | r1과 r2 모두를 원소로 갖지 않는 E들 | Ø |

마지막 열의 집합들은 partition{{w1}, {w2, w3, w4}} 이 generate하는 F1 내에 속하게 된다. 




##### t =2 일때 Ft

앞의 분석을 여기서 다시 하면 다음과 같은 결과를 얻을 수 있다. 

| E의 그룹 | 그룹의 성격 | 그룹내 모든 E 들의 역상 |
|:-:|:-:|:-:|
| E1 | r1 을 원소로 갖는  E들 | {w1} |
| E2 | r2 을 원소로 갖는  E들 | {w2} |
| E3 | r3 을 원소로 갖는  E들 | {w3, w4} |
| E12 | r1과 r2를 동시에 원소로 갖는 E들 | {w1, w2} |
| E13 | r1과 r3를 동시에 원소로 갖는 E들 | {w1, w3, w4} |
| E23 | r2과 r3를 동시에 원소로 갖는 E들 | {w2, w3, w4} |
| E123 | r1, r2, r3를 동시에 원소로 갖는 E | {w1, w2, w3, w4} |
| En | r1, r2, r3를 원소로 갖지 않는 E | Ø |

 

확인해보면 마지막 컬럼의 집합들은 {{1},{2},{3, 4} }이 Generate하는 Sigma algebra의 원소들이다. 

이제 어느 정도 요령이 생기고 규칙 같은 것들이 생길 것이다. 쉽게 말하면 Sample space를 partition 해서 Sigma Algebra Ft들을 generate하는 것이다. <mark>t가 증가함에 따라 partition을 좀더 세분화 하면 Ft1⊆Ft2⊆Ft3… 이런식으로 Filtration 을 만들 수 있다.</mark>





#### 좀더 현실적인 예
좀더 많이 볼 수 있는 Random process 에 적합한 예를 만들어 보자. 동전을 던져서 앞이 나오면 1 뒤가 나오면 0을 점수에 더하는 것으로 하자. 점수는 random process(라고 보아도 되는 것)이다.  동전던지기는 (최대) 3회까지 하는 것으로 하자. Sample space Ω 는 다음과 같이 구성할 수 있다. 

<pics>

동전던지기 첫회 시행에 위, 그 다음 시행에 아래, 그 다음 시행에 위가 나오는 경우는 Wudu 이라고 보면 된다. T=0 시점은 동전던지기를 시행하기 전이다. 

각 동전던지기 수행 시점에서 Random process인 점수를 다음 테이블에 표시하였다.

<pics>

앞의 예제들로 요령이 생겼으니 각각의 시점에서 해당 Sigma – algebra를 얻을 수 있을 것이다. T=0 일 경우에는 { Ø, Ω } 가 generate하는 Sigma-algebra이고 t=1 인 경우에는 Ω 를 1인 값과 0인 값으로 partition을 하고 그것으로부터 Sigma-algebra를 생성(generate)할 수 있다.

각각에 대해서 증대하는 Sigma – algebra인 filtration을 볼 수 있으면 random process가 Ft에 measurable이라는 것이 어떠한 것인지 적어도 논리적으로 알 수 있을 것이다. 

#### 정보 집합으로서의 Filtration
Stochastic process에서 나오는 이론적인 case에서는 위의 예제를 머리 속에서 굴려보면 충분히 이해가 될 듯 싶다. 그런데 간간히 들리는 이야기는 Filtration을 시장을 움직이는 정보들의 모임이라고 보는 견해가 있다. 이것을 알면 증대해 나가는 Sigma algebra에 대한 색다른 관점을 가지게 되는 것이고 또한 금융수학이 목적이면 우리가 사는 세상과 이 수학적 모델이 어떤 연결고리를 가지고 있는 것인지를 알아볼 수 있는 기회가 된다고 생각된다. 

3개의 현실세계에서 주식가격을 움직이는 사건이 있다고 치자. 

A. 2000년 4월 금리인하조치 발표 – 발생될 경우 주식가격 10% 상승
B. 2001년 9월 11일 뉴욕 무역센터 건물 붕괴 – 발생될 경우 주식가격 30% 하락
C. 2002년 3월 예상을 웃도는 회계실적 발표 – 발생될 경우 주식가격 15% 상승

일어난다면 대문자 일어나지 않는다면 소문자로 표기하면 WABc는 A는 일어나고 B도 일어나고 c는 일어나지 않는다는 case이다. 

위의 세 사건말고는 절대 주식가격이 움직이지 않는다고 가정한다. 

<pics>

1.	1999.12 에는 Sigma Algebra가 { Ø, Ω } 이었다. 모든 사건들의  case는 아직 일어나지 않았다. 
2.	2000년 4월에  Sigma Algebra는 { {WABC, WABc, WAbC, WAbc}, {WaBC, WaBc, WabC, Wabc}}이라는  partition이 Generate하는 것이다. W의 첨자 중에서 첫번째 첨자가 가격을 결정한 것이다. 100원이 될지 110원이 될지는 첫 번째 첨자에 해당하는 사건의 정보가 나타났기 때문이다. 다시 말하면 2000년 4월에 100원 또는 110원을 결정하는 것은 2000년 4월에 일어난 ‘사건’이다.  이런 식으로 점점 잘게 partition 을 쪼개어 나가고 그것이 generate하는 것이 Filtration 이고 정보가 점점 증가된다.
3.	위의 모델을 잘 살펴보면 특정시점의 주식가격의 결정은 그때까지의 모든 발생된 정보에 의해서 결정된다. 2001년 9월 직후의 주식가격은 첨자A와 첨자 B에 해당하는 사건발생여부의 ‘정보’가 가격을 결정한다. 

#### Natural Filtration
1.	실제로는 주식가격을 결정하는 정보는 무한이고 그에 따른 주식가격의 변화도 연속적으로 바뀐다. 하지만 모든 정보의 결과가 주식가격으로 나타나니까. t시점의 정보의 변화는 t시점의 가격으로 반영이 된다. Sigma algebra가 어떤 partition에 의해 generate되는 것이라면 그 partition들을 이루는 집합들은 마치 t시점의 주식가격을 index처럼 가지고 있는 것처럼 만들어야 한다. 다시 말하면   partition내의 집합마다 각각 다른 St값을 가지고 있어야 한다. 이를테면 { …{St=99, …}, {St=100…}, {St=101…}, …} 이런 식으로 partition을 하면 된다. 
2.	t에서 dt만큼 지난 t’ 시점에서는 위의 각각의 partition 들을 다시 각각 쪼갠다. 쪼개는 방법은 각각의 partition의 집합들이 St와 St’ 2개의 index로 가지도록 하면 된다. 이렇게… {…{St=99, St’=99…}, {St=99, St’=100…}, {St=99, St’=101},… {St=100, St’=99…}, {St=100, St’=100…}, {St=100, St’=101},… ,{St=101, St’=99…}, {St=100, St’=100…}, {St=99, St’=101}…} 이런 식으로 말이다. 
3.	위의 식을 간략하게 말해보자. 첫 번째 t에서의 Partition(또는 책에 따라서는 Decomposition이라고 하기도 하더구먼)을 D(St)라고 표현해본다. St가 generate 하는 Partition이라고 생각하면 된다. 구체적인 방법은 위에 설명했다. T’에서는 어떻게 될까? D(St, St’) 두 개의 주식가격(또는 Random variable)에 의해서 generate되는 partition인 것이다. 
4.	일반적으로 보면 D(S0, S1, S2,….St)가 된다. T시점의 Sigma algebra Ft는 D(S0, S1,S2, …St)가 generate하는 Sigma-algebra이다. 이것을 σ(S0, S1, S2…St)라고 표시한다. 

마지막 절을 다룬 것은 몇몇의 다른 책에 위와 같은 notation이 있기 때문이다. 




### EPILOGUE
하여튼지 수학책에는 St까지의 Random process가 generate하는 partition이니 Decomposition이니 또 그것이 Generate하는 Sigma-algebra니… 이러니까. 논리적으로는 깔끔해 보이지만 그게 눈으로 들어오기까지는 참으로 죽을 맛이더라. 하긴 이렇게 깔끔한 표현이 도움이 되긴 한다. 앞에서도 말했지만 앞에서 13페이지가 넘게 주저리주저리 써 놓은 것을 수학책에서는 몇 줄로 표현을 하니까.. 깔끔스럽기는 이보다 더하지는 못할 것이다. 많이 생각한 수학의 정의는 대부분 암기하게 되는데… 그게 외우려고 외워지는 것이 아니다. 애매한 예들을 적용하려고 Definition을 수십 번 들춰보게 되는데 그러면 자연스럽게 토씨 하나까지 암기 하게 된다. 이것은 토씨 하나에 따라 정말 많은 것이 좌우되기 때문인데 이때마다. 수학적 정의가 얼마나 정교하게 만들어진 것인지를 새삼 깨닫게 된다. 그렇다 하더라도 개인적으로는 수학자들에게 불만이 많다. 깔끔하게 써 놓은 것도 이해는 가지만, 좀 이해하기 좋게 주저리주저리 쓰는 개인교습교재를 함께 만들었으면 하는 바람 때문이다. 말이 나왔으니 말인데, 수학책들은 두께는 얇으면서도 내용은 많고 비싸기로 유명하다. 비싼 것은 대중적이지 않으니까 그렇다 쳐도, 내용이 많은 것은 그 많은 내용을 압축해서 썼기쓰여졌기 때문이다. 고딩 때 정석책도 그런 식으로 쓰면 아마 책 내용이 1/7로 줄을 것 같다. 반대로 중편소설책 같은 분량의 수학책도 고딩 때 정석책처럼 주저리주저리 설명을 하려면 아마도 백과사전 책의 몇 권이 될 것 같다. 실제로 수학책의 강의노트들은 두꺼운 파일로 정리해도 네댓 개는 나온다. 강의노트 없이 그리고 정식 수학과정을 밟지 않은 공돌이가 맨땅에 헤딩해보니까. 나오는 것은 머리에 피나는 일밖에 없더라. 방법은 그저 조금 더 생각해 보고 써보고 낮은 포복이라도 멈추지 않고 기어가는 길일 것이다. 그래도 이렇게 쓰는 일로 해서 다른 사람들이 좀더 빨리 이해하고 도움이 되면 그간의 고통이 보람이 될 것이라고 믿는다. 여기의 모든 예들은 본인이 직접 고안한 것이다. 뭐, 저작권을 이야기 하려는 것은 아니고 다만 공인된 내용이 아니라(그래도 곡학아세로 혹세무민하는 일은 결코 없다.)그래도 수학이니 엄밀성을 요하는 부분에 부족한 점이 있을 수 있다는 것을 말하려는 것이다. 해서 보다 고수님들이 이 부분을 지적해 주면 더할 나위 없이 고맙겠다. 또한 충분히 설명을 하려고 했으나, 생각지 못한 부분이 있을 수 있으니 보다가 모르는 부분이 있으면 같이 생각하는 것도 또한 쌍방의 유익이 될 것도 같다. 하나 알아둘 것은 본 내용은 Self-Contained이지 않다. 무슨 이야긴고 하면 Sigma-algebra이고 measure고 Random Process이고 생판 모르는 사람이 본 이 내용을 보고 예수가 장님 눈뜨게 하듯 번쩍 뜨일 것 같지는 않을 것 같다는 말이다. 적어도 한번은 수학책을 보고 고민해서 이 생각 저 생각쯤은 한번쯤 한 사람들에게 도움이 되지 않을까? 

아직은 장마다. 주룩주룩 내리는 비속에서 스타벅스같은 데서 노트북이나 두드리는 한가함을 기대해보면서 이만 펜을 놓는다.  

