# NoName


모먼트, MLE (2차까지 확인)

MLE 불변성

MSE를 통해 통계량 성능 비교 가능함
bias

MSE = precision + accuracy

UMVUE 7.5

크래머-라오 부등식 : 최저 분산 뽑아내는 수단

피셔 정보

2차원 피셔 정보

라오-블랙웰 : uniform better UE 뽑아내는 수단

unique best UE

best UE는 오직 하나뿐

(레만쉐페) CSS에 기반한 UE는 오직 유일함

W가 best UE면 W는 다른 모든 0에 대한 추정자들과 무연관 7.7

consistent (점근성)

충분통계량에 기반한 가설검정은 원본데이터 가설검정과 결과 동일

test으 unbaised 8.8

네이만 피어슨

카를린 루빈 8.3

빅 샘플 추정자들과 8.5 

스코어 스탯 8.12

왈드 테스트 8.13


1-a confidence iterval = acceptance region of level 알파 test

뒤집은 테스트의 성질은 컨피던스 인터벌에도 전이됨

pivotal 주어진 X랑 모수로 다른 변량 만들었을 때 이것이 오리지널 모수와 무관한 분포 따름. CLT.

MLE는 asymptotic 성질 갖음. MLE를 asymptotic 했을 때 이는 정규분포 따름. 따라서 MLE의 함수는 추축변량. 

cdf는 출신과 무관하게 U(0,1)을 따르므로 이를 추축변량으로 삼는게 가능. 이떄 자주 쓰이는건 알파/2.

감마와 포아송간 변환



유니모달 cdf가 이하의 조건을 지키면 shortest. 9.5.



dog-tired







Bubble Plot
3D Scatter Plot
Star Plot
Chernoff Faces
Parallel Coordinate Plot

1.Q-Q Plot
Shapiro-Wilks Test
Kolmogorov-Smirnov Test
Skewness Test ( )
Kurtosis Test: ( )
Lin and Mudholkar

Scatter Plot
Squared Generalized Distances
Chi-Square Plot (Gamma Plot)

nqplot
contour plot
cqplot

(Python – assumption check)



